openapi: 3.0.1
info:
  title: Pineslack Coupons API
  version: v1
  description: Coupons API
  contact:
    name: Pineslack
    url: https://www.pineslack.com
    email: coupons@pineslack.com

servers:
  - url: http://localhost:8081
    description: Coupons API server url

paths:
  /api/coupons/v1/websites/{websiteId}/customers/{customerId}:
    post:
      summary: Create coupon
      operationId: createCoupon
      parameters:
        - name: websiteId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/WebsiteId'
        - name: customerId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/CustomerId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/CreateFixedAmountCouponRequest'
                - $ref: '#/components/schemas/CreatePercentageCouponRequest'
                - $ref: '#/components/schemas/CreateFreeProductCouponRequest'
                - $ref: '#/components/schemas/CreateFreeShippingCouponRequest'
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCouponResponse'

  /api/coupons/v1/websites/{websiteId}/customers/{customerId}/coupons/{couponCode}:
    post:
      summary: Redeem coupon
      operationId: redeemCoupon
      parameters:
        - name: websiteId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/WebsiteId'
        - name: customerId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/CustomerId'
        - name: couponCode
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/Code'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RedemptionRequestBody'
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RedemptionResponse'

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    CreateCouponRequestBody:
      type: object
      discriminator:
        propertyName: couponType
        mapping:
          fixed_amount: '#/components/schemas/CreateFixedAmountCouponRequest'
          free_product: '#/components/schemas/CreateFreeProductCouponRequest'
          percentage: '#/components/schemas/CreatePercentageCouponRequest'
          free_shipping: '#/components/schemas/CreateFreeShippingCouponRequest'
      properties:
        couponType:
          $ref: '#/components/schemas/CouponType'
        description:
          $ref: '#/components/schemas/Description'
        usageLimit:
          $ref: '#/components/schemas/UsageLimit'
        multiUser:
          $ref: '#/components/schemas/MultiUser'
        eligible:
          $ref: '#/components/schemas/Eligible'
        expireAt:
          $ref: '#/components/schemas/ExpireAt'
        validFrom:
          $ref: '#/components/schemas/ValidFrom'

    CreateFreeProductCouponRequest:
      allOf:
        - $ref: '#/components/schemas/CreateCouponRequestBody'
        - type: object
          properties:
            freeProducts:
              type: array
              items:
                $ref: '#/components/schemas/Product'

    CreatePercentageCouponRequest:
      allOf:
        - $ref: '#/components/schemas/CreateCouponRequestBody'
        - type: object
          properties:
            percentage:
              $ref: '#/components/schemas/Percentage'

    CreateFixedAmountCouponRequest:
      allOf:
        - $ref: '#/components/schemas/CreateCouponRequestBody'
        - type: object
          properties:
            amount:
              $ref: '#/components/schemas/Amount'

    CreateFreeShippingCouponRequest:
      allOf:
        - $ref: '#/components/schemas/CreateCouponRequestBody'
        - type: object

    CreateCouponResponse:
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          properties:
            coupon:
              $ref: '#/components/schemas/Coupon'

    Response:
      type: object
      properties:
        status:
          $ref: '#/components/schemas/Status'

    Status:
      type: object
      properties:
        code:
          type: string
        message:
          type: string

    # Redemptions
    RedemptionRequestBody:
      type: object
      properties:
        cart:
          $ref: '#/components/schemas/Cart'

    RedemptionResponse:
      allOf:
        - $ref: '#/components/schemas/Response'
        - type: object
          properties:
            redemption:
              $ref: '#/components/schemas/Redemption'

    Redemption:
      type: object
      properties:
        code:
          $ref: '#/components/schemas/Code'
        websiteId:
          $ref: '#/components/schemas/WebsiteId'
        ownedByCustomerId:
          $ref: '#/components/schemas/CustomerId'
        redeemedByCustomerId:
          $ref: '#/components/schemas/CustomerId'
        couponType:
          $ref: '#/components/schemas/CouponType'
        usageLimitBalance:
          $ref: '#/components/schemas/UsageLimit'

    PercentageRedemption:
      allOf:
        - $ref: '#/components/schemas/Redemption'
        - type: object
          properties:
            percentage:
              $ref: '#/components/schemas/Percentage'

    FixedAmountRedemption:
      allOf:
        - $ref: '#/components/schemas/Redemption'
        - type: object
          properties:
            amount:
              $ref: '#/components/schemas/Amount'

    FreeProductRedemption:
      allOf:
        - $ref: '#/components/schemas/Redemption'
        - type: object
          properties:
            freeProducts:
              type: array
              items:
                $ref: '#/components/schemas/Product'

    FreeShippingRedemption:
      allOf:
        - $ref: '#/components/schemas/Redemption'
        - type: object

    # Coupons
    Coupon:
      type: object
      properties:
        code:
          $ref: '#/components/schemas/Code'
        websiteId:
          $ref: '#/components/schemas/WebsiteId'
        customerId:
          $ref: '#/components/schemas/CustomerId'
        couponType:
          $ref: '#/components/schemas/CouponType'
        usageLimit:
          $ref: '#/components/schemas/UsageLimit'
        description:
          $ref: '#/components/schemas/Description'
        multiUser:
          $ref: '#/components/schemas/MultiUser'
        eligible:
          $ref: '#/components/schemas/Eligible'
        expireAt:
          $ref: '#/components/schemas/ExpireAt'
        validFrom:
          $ref: '#/components/schemas/ValidFrom'

    FixedAmountCoupon:
      allOf:
        - $ref: '#/components/schemas/Coupon'
        - type: object
          properties:
            amount:
              $ref: '#/components/schemas/Amount'

    PercentageCoupon:
      allOf:
        - $ref: '#/components/schemas/Coupon'
        - type: object
          properties:
            percentage:
              $ref: '#/components/schemas/Percentage'

    FreeProductCoupon:
      allOf:
        - $ref: '#/components/schemas/Coupon'
        - type: object
          properties:
            freeProducts:
              type: array
              items:
                $ref: '#/components/schemas/Product'

    FreeShippingCoupon:
      allOf:
        - $ref: '#/components/schemas/Coupon'
        - type: object
          properties:
            freeShipping:
              type: boolean

    # Fields

    Eligible:
      type: object
      properties:
        productIds:
          type: array
          items:
            type: string
          example: [ 5a3d8d0b-9f0b-4f6b-9c20-5a7d8c0b5c8d, 5a3d8d0b-9f0b-4f6b-9c20-5a7d8c0b5c8e ]
        categoryIds:
          type: array
          items:
            type: string
          example: [ 5a3d8d0b-9f0b-4f6b-9c20-5a7d8c0b5c8d, 5a3d8d0b-9f0b-4f6b-9c20-5a7d8c0b5c8e ]
        minimumAmount:
          $ref: '#/components/schemas/Amount'
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
    Cart:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        productIds:
          type: array
          items:
            type: string
          example: [ 5a3d8d0b-9f0b-4f6b-9c20-5a7d8c0b5c8d, 5a3d8d0b-9f0b-4f6b-9c20-5a7d8c0b5c8e ]
        categoryIds:
          type: array
          items:
            type: string
          example: [ 5a3d8d0b-9f0b-4f6b-9c20-5a7d8c0b5c8d, 5a3d8d0b-9f0b-4f6b-9c20-5a7d8c0b5c8e ]
        amount:
          $ref: '#/components/schemas/Amount'

    Amount:
      type: object
      properties:
        value:
          type: number
          example: 10
        currency:
          $ref: '#/components/schemas/Currency'
    Product:
      type: object
      properties:
        productId:
          type: string
          example: 5a3d8d0b-9f0b-4f6b-9c20-5a7d8c0b5c8d
        quantity:
          type: number
          default: 1
          example: 2
    Percentage:
      type: integer
      minimum: 1
      maximum: 100
      example: 50
      description: |
        Coupon percentage. Value must be between 1 and 100.
    WebsiteId:
      type: string
      description: Service website.
      example: pineslack
    CustomerId:
      type: string
      description: |
        Unique customer identifier.
      example: 5a3d8d0b-9f0b-4f6b-9c20-5a7d8c0b5c8d
    CouponType:
      type: string
      description: |
        Coupon type: free_shipping, free_product, percentage, fixed_amount
      example: fixed_amount
    Code:
      type: string
      example: E3B0C44298FC1C149A
      description: |
        Unique coupon code that belongs to service websiteId. Customers will use this code
        to redeem a coupon.
    Description:
      type: string
      description: |
        Coupon description.
    Currency:
      type: string
      description: |
        Coupon currency.
      example: USD
    MultiUser:
      type: boolean
      default: false
      description: |
        If a coupon can be redeemed by any customer. By default only one customer can redeem a coupon.
      example: true
    UsageLimit:
      type: integer
      default: 1
      minimum: 1
      description: |
        Coupon usage limit. By default coupon can be used only once.
      example: 3
    ExpireAt:
      type: string
      description: |
        Coupon expiration date.
      example: 2025-09-30T15:30
    ValidFrom:
      type: string
      description: |
        Coupon start date.
      example: 2024-09-30T15:30